### ISSUE TITLE
Mixed up attributes in response

### ISSUE THREAD

**Issue by MichelSc** [Ficodes/quantumleap-source-operator#17]
When several attributes are requested in the settings, the code makes in the to be returned data an attributes for every requested attribute (ok) but the attributes in the data receive values from the wrong attributes (nok).

Error is on line 226 of main.js: the code makes the assumption that the attributes have the same position in the request and in the response. This assumption is not correct.
   ```
         data.forEach((attribute, i) => {
                attribute.values = attribute.values.concat(response.response.attributes[i].values);
            });
```
So we need to look up in the response for the right attribute. This is the fix:
```
            data.forEach((attribute, i) => {
                let response_attribute = response.response.attributes.find(a => a.attrName===attribute.attrName);
                attribute.values = attribute.values.concat(response_attribute.values);
            });
```

**Comment by aarranz** [comment]
Hi @MichelSc,

Thanks for reporting! We will fix this as soon as possible.

**Comment by aarranz** [comment]
Fix merged. Thanks again!
